services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mazir-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    networks:
      - mazir-network

networks:
  mazir-network:
    driver: bridge
